-include .env

build:; forge build

 
deploy-sepolia:
	forge script script/DeployFundMe.s.sol:DeployFundMe \
	--rpc-url $(SEPOLIA_RPC_URL) --private-key $(PRIVATE_KEY) \ 
	--broadcast --verify --etherscan-api-key $(ETHERSCAN_API_KEY) -vvvv

gas-price:; forge snapshot


NETWORK_ARGS := --rpc-url http://localhost:8545 --private-key $(DEFAULT_ANVIL_KEY) --broadcast

ifeq ($(findstring --network sepolia,$(ARGS)),--network sepolia)
	NETWORK_ARGS := --rpc-url $(SEPOLIA_RPC_URL) --private-key $(PRIVATE_KEY) --broadcast --verify --etherscan-api-key $(ETHERSCAN_API_KEY) -vvvv
endif

deploy:
	@forge script script/DeployFundMe.s.sol:DeployFundMe $(NETWORK_ARGS)